name: Django CI

on: 
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
jobs:
    run_django_tests:
        name: Install requirements
        runs-on: ubuntu-latest
        steps:
            - name: Update
              run: sudo apt update