name: Django CI

on: 
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
jobs:
    run_django_tests:
        name: Install requirements
        runs-on: ubuntu-latest
        steps:
            - name: Update
              run: sudo apt update
            - name: Check out repository code
              uses: actions/checkout@v3
            - name: Install pip
              run: sudo apt install python3-pip
            - name: Install requirements
              run: pip install -r requirements.txt
            - name: Test the functions
              run: python manage.py test